name: PDF Essay Checker
description: PDF Essay Checker using GitHub Actions

inputs:
  repository-path:
    description: Relative path under $GITHUB_WORKSPACE where the repository is checked out
    default: ''
  file-glob:
    description: Pattern to match changed files to be considered (relative to repository-path)
    default: '**/*.pdf'
  token:
    description: The token that is used to interact with the GitHub API
    default: ${{ github.token }}
  min-word-count:
    description: Minimum word count that is required to pass the checks
    default: -1
  max-word-count:
    description: Maximum word count that is required to pass the checks
    default: -1
  require-all-pass:
    description: Whether all matched file should pass the checks
    default: false
  report-action-status:
    description: Whether to report the final result as the status (exit code) of the action
    default: true
  require-all-pass:
    description: Whether to require all matched files to pass checks, instead of only one
    default: false
  report-pr-comment:
    description: Whether to report the results as a comment on the pull request
    default: false


outputs:
  word-count:
    description: Number of words in the file

runs:
  using: node12
  main: main.js

branding:
  icon: file-text
  color: orange
